### ISSUE TITLE
Account reorder unreliable

### ISSUE THREAD

**Issue by rsbrux** [protz/Manually-Sort-Folders#150]
I had high hopes for the new account reorder feature, as I find the default ordering of accounts by creation order a real PITA.
Unfortunately, when I tried to change the position of two accounts in Thunderbird 68.10.0 (64-bit), only the first account was moved. Several subsequent attempts to move the second one have produced no results.  I wish to exchange the second account with the one above it, the same change which succeeded with the first account. I have tried moving the lower one up and moving the upper one down.  I have tried using the button to "Restart Thunderbird" and have also tried using the "Close" button after reordering and then closing and reopening Thunderbird manually.  No warnings or other error indications appear; the order simply remains unchanged.

**Comment by itagagaki** [comment]
That's strange... If you have any other add-ons, do you disable all of them and still have the same situation?
I can't think of what else might be causing the issue right now, but if I do come up with something, I might ask you to provide some information to help me find the cause.

**Comment by rsbrux** [comment]
I tried disabling all other add-ons, restarting Thunderbird, swapping the two recalcitrant accounts (4th and 5th in my account list) again and restarting Thunderbird again.  The results are still the same, namely none.  Interestingly, I can still swap the other two accounts (1st and 2nd in the Thunderbird accounts list) that I swapped before, even with all add-ons enabled.
Please let me know what other information you need.

**Comment by itagagaki** [comment]
Hmmm, I see.
Could you please try the following?
1. Press Ctrl+Shift+I to open the Development Toolbox
2. Open the Console pane of the Development Toolbox
3. Open the Manually sort folder in Thunderbird

The console will print out a series of lines like the following.

> xxxxxx tbsortfolders.ui DEBUG xxxxxxxxxxxxxxxxxxx

Can you copy it and show it to me?
*However, this includes privacy, so please replace any part you do not want to be seen with asterisks or something else.

**Comment by itagagaki** [comment]
@rsbrux 
Sorry, I couldn't find the cause of the issue.
Don't you plan to update your Thunderbird to the latest version?
In Thunderbird 91, the account management has been greatly improved, so this issue may have been resolved. And you can now sort your accounts in the Account Settings UI.
Thus, you no longer need to use this add-on to sort your accounts, but you can continue to use it to sort your folders, etc.
This add-on has also been updated to version 2.1.0, so please update it if you like and let me know the result.
Because I want to close this issue.

Manually sort folders version 2.1.0 is available on [ATN](https://addons.thunderbird.net/addon/manually-sort-folders/)

**Comment by rsbrux** [comment]
@itagagaki 
I am now up to Thunderbird 78.13.0.  I haven't seen Thunderbird 91, perhaps because I am still running Ubuntu Studio 18.10.
As you can see, I am way behind with my updates, so there is no point in blocking you.  Please close the issue.  If I still have problems with newer versions of Ubuntu and Thunderbird, I will open a new one.
Many thanks for your support!

**Comment by itagagaki** [comment]
@rsbrux
Thanks for letting me know what's going on.
Strange as ever, you are always welcome to write new issues.
